### PR TITLE
Arc 105: Search

### PR DESCRIPTION
**Pull request by tjboswell**
Should be good on the frontend-end. Just waiting to wire up w/the backend for the actual search

### CODE REVIEW

**Comment by tjboswell** [comment]
This is ready to test 🎉

**Comment by mr2ert** [comment]
What's the current status of this?  How much more testing is needed?

**Comment by tjboswell** [comment]
This should be good to go, I think we've done enough testing for now. If anything comes up we can just make a ticket for it

**Comment by mr2ert** [comment]
:shipit:

**Pull request merged**
