### PR TITLE
ARC-147: Sort Name By Column

### PR DESCRIPTION
**Pull request by y0ungy3**
Works for "Title" and "Author" but for "Date added" it sort by the number, not actual date, so '05/07/2020' would come after '01/12/2012' since 1 comes before 5....when it should be 2020 before 2012......easy fix would be to display 'Year/month/day' for the file list then it should work fine.....

### CODE REVIEW

**Comment by mr2ert** [comment]
Can we pass in a custom compare method to `sortHTML`?  We are going to want this when we add in more types.

**Comment by y0ungy3** [comment]
we're going to add more columns to the main list?

**Comment by tjboswell** [comment]
Aren't we doing the sorting on the backend? If you have multiple pages, we don't want to sort 1 page at a time. And even if we're doing it on the frontend, we definitely don't need a third party library to do this. Sorting html elements is not the way we should do it. We should be using something like `sort()` on the items with custom sort methods.

**Comment by mr2ert** [comment]
@y0ungy3 Ideally, the user will be able to select what columns appear in the main file list.

@tjboswell You are completely correct, seeing the method railroaded my thinking on it.  @y0ungy3 When you sort, we'll want to make an api-call to the backend + refresh the list.  Add the `sort_column` and `sort_order` to the query params for getting all the docs.  I'll wire those in today b/c they'll be really quick.

**Pull request closed without merging**
