### PR TITLE
ARC 119: Login Page Visuals

### PR DESCRIPTION
**Pull request by y0ungy3**

### CODE REVIEW

**Comment by mr2ert** [comment]
Can you add a little gif and/or screenshots of this?

**Comment by y0ungy3** [comment]
ezgif com-video-to-gif

**Review by mr2ert — CHANGES_REQUESTED** [review]
This is really neat -- though there are a couple of changes we should get in:

1. The "login button" at the beginning should be a part of the logo -- looks weird right now based on how it appears/disappears.
2. The login button has a different font then our other buttons.  We'll have to make a unified button style sometime, but for now lets just get rid of the font change.

There are two problems with centering:
untitled
3. The image off-center issue can be solved with wrapping the logo image with `<center></center>`
4. I dunno how to fix the login field off-center when it is minimizing.

If these become too time consuming, move onto something else, but once these fixes are done :shipit:

**Comment by tjboswell** [comment]
do we really want this animation? it seems frustrating that you need to hover your mouse in order to log in. IMO the login fields should be visible on page load, and the username field should be auto focused. it looks cool but i don't know how practical it is.

**Comment by y0ungy3** [comment]
yeah I mean it really depends on what we're going for, fancy or just basic layout. I've seen other senior design groups & their websites look pretty fancy & nice so that's why I picked something like this to start with, this is just a prototype. But we can get rid of animations and do something with just fields in the center or somewhere on the page.

**Pull request closed without merging**
